change product to hardcoded number fixes #1012 fixes #998 fixes #997
grimme-lab/xtb pull request #1051
Opened 2024-06-11 16:35 UTC by james-qbraid

I had the same compilation error as reference in #1012 , #998,  and #997.

This is clearly some sort of bug in gcc as it is clearly passing an array to product.

Unless I am misunderstanding something, changing to hardcoded numbers should not pose a problem. If desired, I could also do the explicit product. e.g. `(2*ewaldCutD(1) + 1)*(2*ewaldCutD(2) + 1)*(2*ewaldCutD(3) + 1)`

2024-06-11 22:05 UTC, awvwgk requested changes
If these arrays were allocated with the right dimensions there is no need at all to specify the shape.

2024-06-11 22:05 UTC, awvwgk commented on src/gfnff/gfnff_eg.f90
> +  real(wp), intent(in) :: rTrans(3, 125)  !previously rTrans(3, product(2*ewaldCutD + 1))
```suggestion
  real(wp), intent(in) :: rTrans(:, :)
```

2024-06-11 22:05 UTC, awvwgk commented on src/gfnff/gfnff_eg.f90
> +  real(wp), intent(in) :: gTrans(3, 124)  !previously gTrans(3, product(2*ewaldCutR + 1) - 1)
```suggestion
  real(wp), intent(in) :: gTrans(:, :)
```

2024-06-11 23:28 UTC, james-qbraid commented
> If these arrays were allocated with the right dimensions there is no need at all to specify the shape.

I agree. Didn't know if you wanted them explicitly defined for some reason.

2024-06-12 06:34 UTC, awvwgk approved these changes
Thanks for sharing. Looks good to me now.

2024-08-09 20:53 UTC, merged