writing updated coord AND xtbopt.xyz during external driver optimization (including nicer printout)
grimme-lab/xtb pull request #828
Opened 2023-06-27 08:11 UTC by marcelmbn

- write xtbopt.xyz constantly in the external driver mode so that not only "coord"-based external methods can be used for geometry optimization.
- nicer formatting

2023-06-27 08:20 UTC, awvwgk commented on src/extern/driver.f90
> +      call writeMolecule(mol, ich, format=1)
Why is `format=1` hard-coded here?

2023-06-27 10:44 UTC, awvwgk requested changes

2023-06-27 10:44 UTC, awvwgk commented on src/extern/driver.f90
> +      if (exist) then
This will only write the gradient if the geometry mismatches the one for the gradient calculation

2023-08-17 09:29 UTC, MtoLStoN approved these changes

2023-08-17 15:16 UTC, awvwgk commented on src/extern/driver.f90
> +         'gradient'. Reading gradient from: 'gradient'."
Please guard this with `if (printlevel > 0)` to avoid clutter.

2023-08-17 15:20 UTC, awvwgk commented on src/extern/driver.f90
> +         "updated geometry written to:",tmpname
This output should be guarded by `printlevel > 0`

2023-08-17 15:21 UTC, awvwgk commented on src/extern/driver.f90
> +      call generateFileName(tmpname, 'xtbopt', extension, mol%ftype)
We use `xtbopt` for the final optimized structure, but this routine can be called from a single point or hessian calculation. Better use a more neutral filename here.

2023-08-18 14:21 UTC, MtoLStoN requested changes

2023-08-18 14:21 UTC, MtoLStoN commented on src/extern/driver.f90
> +
This is probably a debug line, that should be removed.

2023-08-18 14:21 UTC, MtoLStoN commented on src/extern/driver.f90
> +       if (printlevel > 0) &
This could be a single if statement instead of a nested one.

2023-08-18 14:51 UTC, awvwgk approved these changes
Looks good to me now

2023-08-18 18:04 UTC, merged